import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import Sidebar from "./Sidebar";
import Footer from "./Footer";

export const metadata: Metadata = {
  title: "Constellation Cards",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="container is-fluid">
          <div className="columns">
            <div className="column is-one-quarter">
              <Sidebar />
            </div>
            <div className="column"> {children}</div>
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
