# https://dev.to/raulfdm/deploying-on-netlify-via-github-actions-a-seamless-guide-4a43
# was extremely helpful in setting up this flow

name: "Deploy Easel"

on:
  pull_request:
  push:
    branches: [main]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Build Easel
        run: nix build
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - name: Install Netlify
        run: npm install netlify-cli -g
      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          mkdir out
          cp -r result/* out
          prod_flag=""
          if [ "$BRANCH_NAME" = "main" ]; then prod_flag="--prod"; fi
          netlify deploy \
            --dir out \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }} \
            $prod_flag \
            2>&1 | tee deploy_output.txt
      - name: Generate URL Preview
        id: url_preview
        if: ${{ env.BRANCH_NAME != 'main' }}
        run: |
          NETLIFY_PREVIEW_URL=$(cat deploy_output.txt | grep "Website draft URL: " | cut -d' ' -f5)
          echo "NETLIFY_PREVIEW_URL=$NETLIFY_PREVIEW_URL" >> "$GITHUB_OUTPUT"
      - name: Add Preview URL as PR Comment
        if: ${{ env.BRANCH_NAME != 'main' }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Preview URL: ${{ steps.url_preview.outputs.NETLIFY_PREVIEW_URL }}
          comment-tag: url-preview
