name: "Deploy"

on:
  pull_request:
  push:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source
      uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Install Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v2
    - name: Build Easel
      run: nix build
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: "npm"
    - name: Install Netlify
      run: npm install netlify-cli -g
    - name: Deploy to Netlify
      run: |
        mkdir out
        cp -r result/* out
        prod_flag=""
        if [ "$BRANCH_NAME" = "main" ]; then prod_flag="--prod"; fi
        netlify deploy \
          --dir out \
          --site ${{ secrets.NETLIFY_SITE_ID }} \
          --auth ${{ secrets.NETLIFY_API_TOKEN }} \
          $prod_flag
